### ISSUE TITLE
when mt5 run in portable mode, compile with script not work

### ISSUE THREAD

**Issue by fffweb** [L-I-V/MQL-Tools#1]
If mt5 is  started with  /portable, the mt5 data directory is changed, but  "compile mq5 using script " cannot pass  /portable to metaeditor64.exe, and metaeditor use other data directory. and compilation is failed

**Comment by L-I-V** [comment]
> 

Ok. I will fix this in the next update.

**Comment by fffweb** [comment]
Thanks, "Open in 'MetaEditor'" Menu has this problem too.
