### ISSUE TITLE
MQL5: sinput is not syntax coloured

### ISSUE THREAD

**Issue by mishaxz** [L-I-V/MQL-Tools#11]
the keyword sinput does not get coloured. keywords like input do

**Comment by L-I-V** [comment]
Ok. I'll fix it.

**Comment by mishaxz** [comment]
I also noticed `ushort` is not coloured either (so I assume maybe there are some other primitives with this problem?)

**Comment by mishaxz** [comment]
hmm I now see `ushort` is coloured when it is part of the function parameters

but when it wasn't coloured before I was using it with an input
