### ISSUE TITLE
Problem install: not found extension in Code-OSS 

### ISSUE THREAD

**Issue by vnt-83** [L-I-V/MQL-Tools#12]
Hello. I try install MQL-Tools on VSCode (named Code-OSS) in Manjaro Linux. But search not found it by name.  Instruction from marketplace not work too: run command `ext install L-I-V.mql-tools` not found extension. Please, how I can install this extension?

**Comment by L-I-V** [comment]
Look at [here](https://www.linuxadictos.com/code-oss-vscodium-o-visual-studio-code-que-deberia-instalar-en-linux.html).

**Comment by vnt-83** [comment]
Thank You!!!
I now want to install VSCodium. ))
