### ISSUE TITLE
Comment Generation: ArgumentN saves keystrokes over Argument N

### ISSUE THREAD

**Issue by mishaxz** [L-I-V/MQL-Tools#14]
I know it sounds stupid but when you make a comment and it writes `Argument 1` it would be better to be written as `Argument1`.. maybe it doesn't look as good but when you have 4 arguments, that's a lot of keystrokes to edit those names.. if it is just one word you could just double click on the word and start typing.. saving some time.

**Comment by L-I-V** [comment]
Ok, I'll fix it.
