### ISSUE TITLE
Doc comment doesn't indent to same level as function (for non top-level functions)

### ISSUE THREAD

**Issue by mishaxz** [L-I-V/MQL-Tools#15]
Hi, it's me again - sorry..

This is just a trivial issue but I thought I would report it anyhow. I totally understand if you don't want to fix it.

If you add a new doc comment then it doesn't indent the comment to the same indent level as the function is indented. For example if you do it on a class method declaration.

**Comment by L-I-V** [comment]
Hi mishaxz, is there no indentation at all or is there one, but does not correspond to the indentation of the function?

**Comment by mishaxz** [comment]
you know I guess I would not worry about this issue because after I posted it, I noticed that it really depends on the situation. Sometimes it won't even generate the docs for a method of a class. Sometimes it will but not be indented. Maybe this is not even a completely correct description as I don't pay attention most of the time. But anyhow, I think it works well enough in general for commenting functions and I can always copy existing doc comments from another function.
