### ISSUE TITLE
Autocomplete dont' work

### ISSUE THREAD

**Issue by dragan83** [L-I-V/MQL-Tools#16]
thank you so much for this great extension. I'm having trouble with autocomplete (see attachment)

![MQL error](https://user-images.githubusercontent.com/4625750/209638767-6343f1e2-f836-4b82-b60c-6da9f43b868a.png)

the feeling is that it doesn't recognize ENUMs or eg constants like _Symbol or _Point are not autocompleted.

Can you check please?

Thanks in advance

**Comment by L-I-V** [comment]
Hi dragan83, I will fix it in the next update.

**Comment by dragan83** [comment]
You're the best! Thank you so much 🙏

**Comment by dragan83** [comment]
Hi

any idea when the new release will be pubblished?

I'm very exciting...

Thank you in advance

**Comment by L-I-V** [comment]
Hi dragan83, an update will be published within a few days.
