### ISSUE TITLE
Problem with compiling mqh files.

### ISSUE THREAD

**Issue by RenIfx** [L-I-V/MQL-Tools#20]
Hello. Problem with compiling mqh files. The files are not compiled. An error pops up. 
In the metaeditor everything compiles fine.

![image](https://user-images.githubusercontent.com/91544971/222905751-4574ee71-59e8-40b1-a800-3a2b388acc54.png)

![image](https://user-images.githubusercontent.com/91544971/222904846-f24bf273-07da-48c1-8531-e7ed7c6d13e9.png)

I wrote as it is written in the recommendation, but it did not help.

**Comment by L-I-V** [comment]
What is this 'mh4' file?
Can you provide a screenshot with the first line of the editor and the file name?

**Comment by RenIfx** [comment]
Sorry MQH

![image](https://user-images.githubusercontent.com/91544971/222919359-d6cdd3e4-4f18-4526-bf74-54dbe3465fa4.png)

**Comment by L-I-V** [comment]
What are you trying to achieve by compiling the ‘.mqh’ file? Just to clarify, compiling a ‘.mqh’ file does not result in an executable file, unlike the compilation of a ‘.mq5’ file. Files with the ‘.mq4\.mq5’ extension contain the source code of an expert or an indicator, which must be compiled into an executable file. Files with the ‘.mqh’ extension contain shared functions and constants that can be used in other files.

When you compile a ‘.mqh’ file in MetaEditor, it simply checks for syntax errors. 
If you want to check a file with the ‘.mqh’ extension for syntax errors, you can use the Ctrl+Shift+Z shortcut or click the corresponding button.

If you want to compile the ‘.mq5’ file that includes the ‘.mqh’ file without switching to the ‘.mq5’ file tab, you can insert the name of the ‘.mq5’ file in the first line of the ‘.mqh’ file (for example: //###<Experts/Examples/MACD Sample.mq5). This will allow the compiler to automatically find the ‘.mq5’ file and use it during compilation.

**Comment by RenIfx** [comment]
Now I understand everything.
Please excuse me.
Thanks a lot for your works and your helps.
