### ISSUE TITLE
Intelli Sense Error Squiggles

### ISSUE THREAD

**Issue by trustfultrading** [L-I-V/MQL-Tools#25]
Hi LIV,

When I active the "Intelli Sense Error Squiggles" setting, errors are displayed for variables declared in other files. 
<img width="199" alt="2023-03-27 10_28_39-Settings - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/227887519-228c3bc6-9b90-43d3-b6d2-af3355e6ca9e.png">

The project compiles fine.
They reappear when you click on the include files.
<img width="624" alt="2023-03-27 10_19_01-VSCTestGUI mqh - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/227887770-262b926d-1817-4160-8a21-d37f992341d3.png">

The errors are not displayed when I switch to the "main" file.
<img width="576" alt="2023-03-27 10_23_14-VSCTest mq5 - MQL5 - Visual Studio Code" src="https://user-images.githubusercontent.com/116789180/227887599-24b35b82-3467-4209-8b6c-2f64079edc60.png">

**Here are the files I used:**
[Test.zip](https://github.com/L-I-V/MQL-Tools/files/11076500/Test.zip)

Hope this helps ;)

**Comment by L-I-V** [comment]
Hi trustfultrading, in version 2.0.1, I have fixed this issue. Now the check of 'mqh' files will depend on a similar record '//###<Experts/Test/VSCTest.mq5>' in the first line. This means that the mq4/mq5 file will be checked and the 'mqh' include files will be checked through it.

**Comment by trustfultrading** [comment]
Hi LIV,
just checked and it works fine now. Very nice update, thanks!
