### ISSUE TITLE
Conflicts with VSCode AutoSave feature.

### ISSUE THREAD

**Issue by abdielou** [L-I-V/MQL-Tools#26]
This setting `mql_tools.IntelliSenseErrorSquiggles` is forcing an auto save on VS Code.

Ref: https://github.com/microsoft/vscode/issues/176224#issuecomment-1489049178

**Comment by L-I-V** [comment]
Hi abdielou! That's correct, when this parameter is enabled, the MQL files (mq4/mq5/mqh) are auto saved when they are edited. This is due to the fact that MetaEditor requires files with actual data for checking.

**Comment by abdielou** [comment]
hmmmm I see.
well I don't see any decent workaround that would not mess with VSCode's auto save

tnx
