### ISSUE TITLE
mql4 suggestion doesnt work

### ISSUE THREAD

**Issue by eorl97** [L-I-V/MQL-Tools#30]
hi 
im using your extention for a while now i love it 
you couldnt do a better job 
but lately im facing a annoying problem 
suddenly the vs code wont give me suggestions 
for example when i wanted to set an intiger for object as soon as i wrote OBJ_ your extention  would have give me all the possible suggestion that was very helpfull 
but now it doesnt give me anything 
althou it works fine in my lap top but in my pc its not working 
i tried uninstalling the vs code completily and installing it again i deleted all the saved data folders for vs code but still cant reciving these suggestions. i love your extention if there is solution to this please help me thanks a lot .....

**Comment by L-I-V** [comment]
Hi eorl97, can you show a screenshot of the contents of the 'settings.json' file which is in the '.vscode' folder?

**Comment by eorl97** [comment]
Hello there thank you For your response Here you are 
![JsonSetting](https://user-images.githubusercontent.com/130066738/230439544-cd27fbda-76f5-4920-9e09-f7a020ec5781.png)

**Comment by eorl97** [comment]
![Screenshot 2023-04-06 184509](https://user-images.githubusercontent.com/130066738/230443322-a7da2451-0e83-42a3-8ca3-89ef8169c302.png)
it also gives this error

**Comment by L-I-V** [comment]
In this folder "c:\Users\Usuario\.vscode\extensions\l-i-v.mql-tools-2.0.0\data", are the files 'mql5_en.mqh' and 'mql.mqh' present?
If they are present, try e.g. in the 'Print()' function to go to the definition by pressing 'F12', it should take you to the file 'mql5_en.mqh'. If the file 'mql5_en.mqh' has opened and autocompletion does not work, try to reinstall the 'C/C++' extension and update the 'MQL Tools' extension.
'Do not disable!'  - A simple warning that does not affect anything.

**Comment by eorl97** [comment]
man thank you a lot you are a life saver 
there wasnt any data folder there for no reason i just found the folder in my lap top and transfered it to this location and it solved it now i can see every thing man i had two unfinished project you saved them thanks again
