### ISSUE TITLE
`this.` operator error, vscode expects `this->`

### ISSUE THREAD

**Issue by Maxiviper117** [L-I-V/MQL-Tools#31]
In MQL, obviously to access class instance member variables and function, we can use `this.` operator to it.

```cpp
class MyClass {
public:
    void setValue(int value) {
        this.value = value;
    }
private:
    int value;
};
```

Problem is with c++ intellisense detects this as an issue because it uses the `this->` instead.
Leading to these errors showing from the intellisense.
![image](https://user-images.githubusercontent.com/11472492/230900347-a7ee7ab5-f8c3-418c-98d7-4a825f1f7b4b.png)

I would prefer not to disable the error squiggles, as to allow me to spot other errors as well, but the errors can become lost in a sea of `this.` operator errors. Hoping there is a way to take this into account. If not, then I'm just going to have to deal with it. :)

**Comment by L-I-V** [comment]
Which extension underlines 'this' in the screenshot, 'C/C++' or 'MQL Tools'? Could you show me a screenshot of the error message when you hover the cursor over "this"?

**Comment by Maxiviper117** [comment]
![image](https://user-images.githubusercontent.com/11472492/231690386-db69c9ac-3dad-43b6-853f-ed300864eafe.png)

**Comment by Maxiviper117** [comment]
Here is an example.

![image](https://user-images.githubusercontent.com/11472492/231691241-f8f6d4b6-928e-4f50-9f09-d02f4a2ef63d.png)

![image](https://user-images.githubusercontent.com/11472492/231691145-bdc9108e-446c-444c-89b9-9d5b7638b6ca.png)

No error if `this->` used, but obviously MQL5 doesn't like that.

![image](https://user-images.githubusercontent.com/11472492/231691754-f388e459-ba3f-4b39-98f7-57f9707d8f39.png)

**Comment by L-I-V** [comment]
Hi Maxiviper117, As far as I understand you can't use the error squiggles of the 'MQL Tools' extension because you use MAC and that's why you use the error squiggles of the 'C/C++' extension as an alternative. In this case, insert this code at the beginning of an mq5 or mqh file 
```cpp
#ifdef __INTELLISENSE__
#pragma diag_suppress 153
#endif 
```
This way intellisense c++ will ignore this error. 153 is the error code. The codes can be added separated by commas.
