### ISSUE TITLE
No compilation

### ISSUE THREAD

**Issue by ArihoJedidiah** [L-I-V/MQL-Tools#34]
CTR +Shift+ X not compiling on windows machine. Instead Vs code asks to configure a task in a json settings file.

**Comment by L-I-V** [comment]
You may already be using this keyboard shortcut. Check the 'keybindings.json' file, and if it is there, delete or change it.

**Comment by ArihoJedidiah** [comment]
> You may already be using this keyboard shortcut. Check the 'keybindings.json' file, and if it is there, delete or change it.

deleting fixed the issue.
