### ISSUE TITLE
vector/matrix methods are not shown in intelliSense

### ISSUE THREAD

**Issue by chaploud** [L-I-V/MQL-Tools#45]
Hi. Thank you for your great Extension. I am using your extension for my development in MQL5 on Windows 11.

## Problem

Vector/matrix methods are not shown in intelliSense.

In MetaEditor, vector/matrix methods are shown in completion popup. 

![スクリーンショット 2023-11-25 000458](https://github.com/L-I-V/MQL-Tools/assets/19206115/2dce8344-ce26-47a3-b104-16075e67c231)

## Goal

Vector/matrix methods are shown in intelliSense.

Kind regards.

**Comment by benjamindoerries** [comment]
is it possible to fix this manually or just wait for an update of the extensio ?
