### ISSUE TITLE
MQH Syntax checking not recognizing many MQL functions

### ISSUE THREAD

**Issue by kalotech** [L-I-V/MQL-Tools#5]
What a awesome plugin, I can't wait to ditch MetaEditor for good.  All that is keeping me back now is that when I am in a MQH file, and want to do Syntax checking, a lot of MQL functions are not recognized for example: DoubleToStr  and MarketInfo etc... yet when I am in a MQL4 file, these functions are checked and recognized.

![image](https://user-images.githubusercontent.com/56123637/202726951-c0c21a37-39f7-4a01-b98c-657a4e51557f.png)

![image](https://user-images.githubusercontent.com/56123637/202727098-b7c9cee6-2f9f-48bf-9a91-f503a4b38cfc.png)

**Comment by L-I-V** [comment]
At first glance, I would guess that you didn't read point 1 carefully.
![Screenshot_206](https://user-images.githubusercontent.com/114299712/202757530-dbb7a151-ec57-46f2-a507-46229d40f388.png)
![Folder name](https://user-images.githubusercontent.com/114299712/202757781-51987e89-6fe7-47ef-b477-39baa30f4d5e.png)

**Comment by kalotech** [comment]
Hey L-I-V !  Thanks for getting back so soon and for referring me to the installation steps.  I checked carefully and even did it all from scratch over again and still no luck.

The particular MT4 installation I was using is the portable kind where I use the /portable switch from a custom shortcut.  I did notice in your settings there was a checkbox for such a thing and I even checked that, but still the MQH files does not check out correctly.

Then I made a clean and full installation of MT4 on my computer and when through the whole setup again and i can confirm that after doing so MQH files syntax checking works 100% perfectly.

The issue seems to be with a portable install somehow...not sure where I went wrong.  I could see the .vscode folder your plugin creates and all of that after I open the MQL4 folder in VSCODE.... and I could see inside the json file where MQH is mapped to CPP but for the portable install that still did not work....

I also notice a error in the settings.json file that is created in the vscode folder...not sure if that is a clue... I'll paste a screenshot below.

If there is anything else I can check to get it to play nice with the portable install, it would be great.

Thank you so much for creating such an awesome plugin for VSCODE and most importantly for sharing it freely, your kindness and generosity sincerely appreciated.

![image](https://user-images.githubusercontent.com/56123637/202844582-58257a2d-17f3-4e83-bbfb-4324341d153a.png)

**Comment by L-I-V** [comment]
Thanks for the error information. Indeed, there was a problem when checking the syntax of the 'MQH' file in the '/portable' mode. At the moment, I have fixed the bug and published an update on the Marketplace. About an error in the file 'settings.json', this is not an error, but a warning that does not affect anything.

**Comment by kalotech** [comment]
Hi L-I-V, thanks so much for this, I can confirm that Syntax checking for portable now works 100%, but  now the F1 for Help does not work any more....I see there is already a error ticket opened for something similar, I will add my finding there in a moment.
