### ISSUE TITLE
File is outside the workspace MQL5

### ISSUE THREAD

**Issue by Badzoneyv4n** [L-I-V/MQL-Tools#50]
Hello LIV thank you for this extension, I don't know why i keep gating this "[Error] The file is outside the workspace MQL5"  I'm using linux debian 12. and the mq5 file is in experts folder. Even when I select a . mq5 file and select open with metaeditor meta editor won't open. But when I click any word and f1 for help, mql5 reference opens.

![Screenshot at 2024-02-09 03-52-04](https://github.com/L-I-V/MQL-Tools/assets/138767735/baead92b-520e-4c10-9a17-dfaf9187c502)

**Comment by Badzoneyv4n** [comment]
I think the problem was in the path of MetaEditor64.exe , So I replaced the path with

```
'${workspaceFolder}/../MetaEditor64.exe'
```
in both user and workspace in the extension's settings.

![Screenshot at 2024-02-10 17-03-08](https://github.com/L-I-V/MQL-Tools/assets/138767735/abeb67a5-0bfc-4959-887c-5c1eacc09b5e)

**Comment by kenorb** [comment]
I've tried to set to:

    ${workspaceFolder}/../home/vscode/.wine/drive_c/Program Files/MetaTrader 5/MetaEditor64.exe

but it didn't work either.

> [Error]  'Invalid path to "metaeditor.exe": MQL5' [ /workspaces/home/vscode/.wine/drive_c/Program Files/MetaTrader 5/MetaEditor64.exe ]

**Comment by brenoperucchi** [comment]
@kenorb Did you get a solution?
