### ISSUE TITLE
Color Problem on Compile // testcolor = C '0,0,0';

### ISSUE THREAD

**Issue by IcHiAT** [L-I-V/MQL-Tools#58]
When compiling color still gets automatically a whitespace between C and 'X'. 

Example:

Coded:
color colortest = C'0,0,0';

Compiled:
color colortest = C '0,0,0'; <<<< whitespace between C and '

That results in compiling error.
Happens on actually version (2.1.0) also on older ones.

Screenshot: https://prnt.sc/sTTZ8n7Lxagm

**Comment by IcHiAT** [comment]
My mistake, styler got wrong associated with vscode. Works!

**Comment by Botan626** [comment]
> My mistake, styler got wrong associated with vscode. Works!

there is `close issue` button
![image](https://github.com/L-I-V/MQL-Tools/assets/28785698/c8813890-4c70-41c1-84a0-7a81162b1586)
