### ISSUE TITLE
Go to Definition (F12) missing

### ISSUE THREAD

**Issue by bohacf** [L-I-V/MQL-Tools#9]
The context menu of MQL file has no "Go to Definition (F12)" item (same as Ctrl+click functionality).
This is very important function. Is it possible to add in future version?

**Comment by kalotech** [comment]
![image](https://user-images.githubusercontent.com/56123637/204438499-e1e8084f-a04b-45cb-8042-88ef3f345690.png)

**Comment by bohacf** [comment]
Thanks kalotech, you're right. On clean instalation of VSCode works fine.
(previously was problematic on MQL file type)

But, is any way to configure C++ to accept variables with **input** keyword?

![image](https://user-images.githubusercontent.com/3647818/204554623-7bdff9aa-061f-4e20-b191-d9985cddcc9e.png)

[MACD Sample.mq4.txt](https://github.com/L-I-V/MQL-Tools/files/10113930/MACD.Sample.mq4.txt)

In custom setting for CPP i have only this:
`"C_Cpp.errorSquiggles": "Disabled"`
